import HOCWrapper from "@/_hoc";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BSecure+ Launcher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <Link rel="preconnect" href="https://fonts.googleapis.com" />
        <Link rel="preconnect" href="https://fonts.gstatic.com" />
        <Link
          href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz@8..144&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <HOCWrapper>{children}</HOCWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
